---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-crds-external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: "./external/business-operations/kubernetes/base-apps/secrets/external-secrets/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bv-ops-kubernetes
