---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tryton-admin-ext
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tryton-admin-ext
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: apps/tryton/admin-user
        property: username
    - secretKey: password
      remoteRef:
        key: apps/tryton/admin-user
        property: password
