---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./admin-externalsecret.yaml

configMapGenerator:
  - name: tryton-helm-values
    files:
      - values.yaml

configurations:
  - name-reference.yaml
