nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: HelmRelease
        path: spec/valuesFrom[]/name
  - kind: ConfigMap
    fieldSpecs:
      - kind: HelmRelease
        path: spec/valuesFrom[]/name
