tryton:
  dbHostname: "tryton-db-v2-rw"
  dbName: "tryton"

image:
  pullPolicy: IfNotPresent
  repository: registry.${use_gitlab_system}/bv/code/tryton/nix/nix-bo-tech-tryton/trytond
  tag: v0.16.0@sha256:87ca4e6e66b8ca00a3906abb19b5bd3d1f75492d99bd1e945b9c97b69a1b1eab

postgresql:
  bundled: false

persistence:
  existingClaim: data-tryton

ingress:
  annotations:
    hajimari.io/enable: "true"
  hosts:
    - host: "tryton.${cluster_domain}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ""
      hosts:
        - "tryton.${cluster_domain}"
