tryton:
  dbHostname: "tryton-db-v2-rw"
  dbName: "tryton"

image:
  pullPolicy: IfNotPresent
  repository: registry.${use_gitlab_system}/bv/code/tryton/nix/nix-bo-tech-tryton/trytond
  tag: v0.19.0@sha256:9a42c1d28b07cd636e8e67d86a9999ddb9a94e83de12fce7b0a19d4509a8b571

postgresql:
  bundled: false

persistence:
  existingClaim: data-tryton

ingress:
  enabled: false
