tryton:
  dbHostname: "tryton-db-v2-rw"
  dbName: "tryton"

image:
  pullPolicy: IfNotPresent
  repository: registry.${use_gitlab_system}/bv/code/tryton/nix/nix-bo-tech-tryton/trytond
  tag: v0.15.0@sha256:2144477046d2b34f8bcab80be901ec319864466f8a8fe383a31338225e4aba53

postgresql:
  bundled: false

persistence:
  existingClaim: data-tryton

ingress:
  annotations:
    hajimari.io/enable: "true"
  hosts:
    - host: "tryton.${cluster_domain}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ""
      hosts:
        - "tryton.${cluster_domain}"
