---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/traefik/traefik-helm-chart/traefik/crds?ref=v39.0.8

patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*\\.hub\\.traefik\\.io"
    patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: placeholder
  - target:
      kind: CustomResourceDefinition
      name: ".*\\.gateway\\.networking\\.k8s\\.io"
    patch: |
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: placeholder
