---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code

resources:
  - ../../base/forgejo-data

components:
  - ../../../../../../components/volume/backup-volsync

patches:
  - patch: |-
      - op: replace
        path: /spec/trigger/schedule
        value: "35 2/3 * * *"
    target:
      group: volsync.backube
      kind: ReplicationSource
