---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-mayan-edms
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://registry.${use_gitlab_system}/deployment/mayan-edms-helm/helm
  timeout: 3m
