---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ReplicationSource|ReplicationDestination
      group: volsync.backube
    patch: |
      kind: ReplicationSource
      metadata:
        name: not-used
      spec:
        restic:
          moverSecurityContext:
            runAsUser: 100
