---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/repo-data-gitlab-gitaly-0

components:
  - ../../../../../../components/volume/backup-volsync
  - ../../../../../../components/volume/restore-volsync

patches:
  - patch: |-
      - op: replace
        path: /spec/trigger/schedule
        value: "13 2/3 * * *"
    target:
      group: volsync.backube
      kind: ReplicationSource
