---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-ingress-headers
  namespace: security
data:
  Cache-Control: "no-store"
  Pragma: "no-cache"
  X-Frame-Options: "SAMEORIGIN"
  X-XSS-Protection: "1; mode=block"
