---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ingress-headers-configmap.yaml

commonLabels:
  app.kubernetes.io/name: authelia
  app.kubernetes.io/instance: authelia

configMapGenerator:
  - name: authelia-configmap
    files:
      - configuration.yaml=./config/configuration.yaml
      - access-control.yaml=./config/access-control.yaml

configurations:
  - name-reference.yaml
