---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets

resources:
  - ./data-vault-0
  - ./audit-vault-0

components:
  - ../../components/mover-security-context

patches:
  # Restore is special because we don't have external secrets yet working
  - target:
      kind: ExternalSecret
      group: external-secrets.io
      name: restic-restore.*
    patch: |
      $patch: delete
      kind: ExternalSecret
      metadata:
        name: not-used
