---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-external
resources:
  - ./helmrelease.yaml

configMapGenerator:
  - name: traefik-external-values
    files:
      - values.yaml=./values.yaml

configurations:
  - name-reference.yaml
