---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: registry-mirror-alert
spec:
  groups:
    - name: registry-mirror
      rules:
        - alert: RegistryMirrorEvicted
          annotations:
            summary: Registry mirror {{ $labels.pod }} was evicted, losing syncs in flight
          expr: kube_pod_status_reason{namespace="registry", reason="Evicted"} == 1
          labels:
            severity: critical
        - alert: RegistryMirrorRestarted
          annotations:
            summary: Registry mirror {{ $labels.pod }} restarted, losing syncs in flight
          expr: increase(kube_pod_container_status_restarts_total{namespace="registry", container="zot"}[1h]) > 0
          labels:
            severity: warning
