---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-restore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: restic-restore
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .s3_endpoint }}/{{ .s3_bucket }}"
        RESTIC_PASSWORD: "{{ .repo_password }}"
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_access_key_secret }}"
  dataFrom:
    - extract:
        key: backup/env/${cluster_restore_env}/volsync-restore
