---
storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /data/notification.txt

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: none
  user_verification: discouraged
  timeout: 60s

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
