---
storage:
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain:
        - "apps.${cluster_domain}"
      policy: one_factor
    - domain:
        - "echo-server.${cluster_domain}"
      subject:
        - "group:admins"
      policy: one_factor
    - domain:
        - "gitops.${cluster_domain}"
      subject:
        - "group:admins"
      policy: two_factor
    - domain:
        - "grafana.${cluster_domain}"
      policy: two_factor
      subject:
        - 'group:admins'
    - domain:
        - "hubble.${cluster_domain}"
      subject:
        - "group:admins"
      policy: two_factor
    - domain:
        - "lldap.${cluster_domain}"
      subject:
        - "group:admins"
      policy: two_factor
    - domain:
        - "prometheus.${cluster_domain}"
      policy: two_factor
      subject:
        - 'group:admins'
    - domain:
        - "rook-main.${cluster_domain}"
      policy: two_factor
      subject:
        - 'group:admins'
    - domain:
        - "vault.${cluster_domain}"
      subject:
        - "group:admins"
      policy: two_factor

notifier:
  disable_startup_check: false
  filesystem:
    filename: /data/notification.txt

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: none
  user_verification: discouraged
  timeout: 60s

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
