apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-shell-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitlab-shell-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: secret
      remoteRef:
        key: apps/gitlab/gitlab-shell-secret
        property: secret
