apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-runner-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitlab-runner-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: runner-registration-token
      remoteRef:
        key: apps/gitlab/gitlab-runner-secret
        property: runner-registration-token
    - secretKey: runner-token
      remoteRef:
        key: apps/gitlab/gitlab-runner-secret
        property: runner-token
