apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-minio-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-minio-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: accesskey
      remoteRef:
        key: apps/gitlab/minio-secret
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: apps/gitlab/minio-secret
        property: secretkey
