apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-pages-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitlab-pages-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: shared_secret
      remoteRef:
        key: apps/gitlab/gitlab-pages-secret
        property: shared_secret
