apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-zoekt-basicauth
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-zoekt-basicauth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: gitlab_password
      remoteRef:
        key: apps/gitlab/zoekt-basicauth
        property: gitlab_password
    - secretKey: gitlab_username
      remoteRef:
        key: apps/gitlab/zoekt-basicauth
        property: gitlab_username
