apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations: {}
  name: gitlab-rails-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-rails-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: secrets.yml
      remoteRef:
        key: apps/gitlab/rails-secret
        property: secrets.yml
