apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-suggested-reviewers
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitlab-suggested-reviewers
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: suggested_reviewers_secret
      remoteRef:
        key: apps/gitlab/gitlab-suggested-reviewers
        property: suggested_reviewers_secret
