apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-postgresql-password
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-postgresql-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: apps/gitlab/postgresql-password
        property: postgresql-password
    - secretKey: postgresql-postgres-password
      remoteRef:
        key: apps/gitlab/postgresql-password
        property: postgresql-postgres-password
