apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitaly-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitaly-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: apps/gitlab/gitaly-secret
        property: token
