apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-secret
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-registry-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: registry-auth.crt
      remoteRef:
        key: apps/gitlab/registry-secret
        property: registry-auth.crt
    - secretKey: registry-auth.key
      remoteRef:
        key: apps/gitlab/registry-secret
        property: registry-auth.key
