apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-kas-private-api
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-kas-private-api
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: kas_private_api_secret
      remoteRef:
        key: apps/gitlab/kas-private-api
        property: kas_private_api_secret
