apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-shell-host-keys
  namespace: gitlab
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitlab-gitlab-shell-host-keys
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ssh_host_dsa_key
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_dsa_key
    - secretKey: ssh_host_dsa_key.pub
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_dsa_key.pub
    - secretKey: ssh_host_ecdsa_key
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_ecdsa_key
    - secretKey: ssh_host_ecdsa_key.pub
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_ecdsa_key.pub
    - secretKey: ssh_host_ed25519_key
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_ed25519_key
    - secretKey: ssh_host_ed25519_key.pub
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_ed25519_key.pub
    - secretKey: ssh_host_rsa_key
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_rsa_key
    - secretKey: ssh_host_rsa_key.pub
      remoteRef:
        key: apps/gitlab/gitlab-shell-host-keys
        property: ssh_host_rsa_key.pub
