apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitlab-gitaly-secret.yaml
  - gitlab-gitlab-initial-root-password.yaml
  - gitlab-gitlab-kas-secret.yaml
  - gitlab-gitlab-pages-secret.yaml
  - gitlab-gitlab-runner-secret.yaml
  - gitlab-gitlab-shell-host-keys.yaml
  - gitlab-gitlab-shell-secret.yaml
  - gitlab-gitlab-suggested-reviewers.yaml
  - gitlab-gitlab-workhorse-secret.yaml
  - gitlab-kas-private-api.yaml
  - gitlab-minio-secret.yaml
  - gitlab-postgresql-password.yaml
  - gitlab-rails-secret.yaml
  - gitlab-redis-secret.yaml
  - gitlab-registry-httpsecret.yaml
  - gitlab-registry-notification.yaml
  - gitlab-registry-secret.yaml
  - gitlab-zoekt-basicauth.yaml
