---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restore-certificates
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restore-certificates-edit-secrets
subjects:
  - kind: ServiceAccount
    name: restore-certificates
    namespace: cert-manager
