---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/audit-vault-0

components:
  - ../../../../../../components/volume/backup-volsync
  - ../../../../../../components/volume/restore-volsync

patches:
  - patch: |-
      - op: replace
        path: /spec/trigger/schedule
        value: "47 0/3 * * *"
    target:
      group: volsync.backube
      kind: ReplicationSource
