---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/gitlab-minio

components:
  - ../../../../../../../../external/business-operations/kubernetes/components/volume/restore-volsync
