---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: gitaly
    app.kubernetes.io/instance: gitlab
  name: repo-data-gitlab-gitaly-0
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
