---
- name: Start microVMs on their hypervisor hosts
  gather_facts: false
  hosts: initial_controller:controllers:workers
  tasks:
    - name: Start microVM service
      ansible.builtin.command: >-
        systemctl start microvm@{{ inventory_hostname }}
      delegate_to: "{{ microvm_host }}"

    - name: Wait for VM to become reachable
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        delay: 2
        timeout: 120
      delegate_to: localhost
