service:
  additionalServices:
    git-pages:
      annotations:
        lbipam.cilium.io/ips: "${cluster_git_pages_ip}"
      labels:
        ip-range: static-pool

ports:
  git-pages:
    port: 8444
    expose:
      default: false
      git-pages: true
    exposedPort: 443
