---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

resources:
  - ../../base/data-lldap.yaml

components:
  - ../../../../../../components/volume/backup-volsync
  - ../../../../../../components/volume/restore-volsync

patches:
  - patch: |-
      - op: replace
        path: /spec/trigger/schedule
        value: "23 2/3 * * *"
    target:
      group: volsync.backube
      kind: ReplicationSource
