---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.31.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
    disableHooks: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    disableHooks: false
  uninstall:
    keepHistory: false

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: vault
            patch: |
              - op: remove
                path: /spec/volumeClaimTemplates
              - op: add
                path: /spec/template/spec/volumes/0
                value:
                  name: audit
                  persistentVolumeClaim:
                    claimName: audit-vault-0
              - op: add
                path: /spec/template/spec/volumes/0
                value:
                  name: data
                  persistentVolumeClaim:
                    claimName: data-vault-0

  values:
    global:
      enabled: false
      tlsDisable: true

    injector:
      enabled: false

    server:
      enabled: true
      image:
        tag: 1.20.4@sha256:268bb80aa9c6d13d65fcfa05c0c268caca068952240a8087291a6ce0b66e3a10
      logLevel: "info"
      logFormat: "standard"
      updateStrategyType: RollingUpdate

      extraContainers:
        - name: auto-unseal
          args:
            - |
              if test -n "$(cat /vault/secret-unseal/key)"
              then
                vault operator unseal "$(cat /vault/secret-unseal/key)"
              else
                echo "No unseal key, doing nothing"
              fi
              sleep infinity
          command:
            - /bin/sh
            - -ec
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          image: hashicorp/vault:1.21.1@sha256:f4e2687b72858a9e2160c344c9fa1ef74c07f21a89a8c00534ab64d3f187b927
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /vault/secret-unseal
              name: secret-unseal

      volumes:
        - name: secret-unseal
          secret:
            secretName: vault-unseal
            defaultMode: 0420
            items:
              - key: "key"
                path: "key"

      ingress:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
        ingressClassName: "nginx"
        hosts:
          - host: vault.${cluster_domain}
            paths:
              - /
        tls:
          - hosts:
              - vault.${cluster_domain}

      route:
        enabled: false

      extraEnvironmentVars: {}
      extraSecretEnvironmentVars: []

      dataStorage:
        enabled: true
        size: 1Gi
      auditStorage:
        enabled: true
        size: 5Gi

      dev:
        enabled: false

      standalone:
        enabled: true

    ui:
      enabled: true

    csi:
      enabled: false
