---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
  labels:
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: minio
    app.kubernetes.io/managed-by: Helm
  name: gitlab-minio
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
