---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - httproute.yaml

configMapGenerator:
  - name: git-pages-config
    files:
      - config.toml
