---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-base-apps-vault-volumes
  namespace: flux-system
spec:
  interval: 10m
  path: "./external/business-operations/kubernetes/base-apps/secrets/vault-volumes/overlays/${cluster_bootstrap_mode}"
  prune: true
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: audit-vault-0
      namespace: secrets
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-vault-0
      namespace: secrets
  sourceRef:
    kind: GitRepository
    name: bv-ops-kubernetes
  dependsOn: []
