apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: volsync-view
rules:
  - apiGroups:
      - volsync.backube
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
