---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unifi
  namespace: flux-system
spec:
  path: ./external/business-operations/kubernetes/apps/default/unifi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: bv-ops-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-unifi-volumes

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unifi-volumes
  namespace: flux-system
spec:
  interval: 10m
  path: ./external/business-operations/kubernetes/apps/default/unifi/volumes/overlays/${cluster_bootstrap_mode}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: bv-ops-kubernetes
