---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
spec:
  interval: 24h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: 16.2.0
    digest: sha256:472df7d769db2f79bbb4714441b758c198d40f872c94e65afc25b19ec5291930
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: forgejo
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  valuesFrom:
    - kind: ConfigMap
      name: forgejo-helm-values
      valuesKey: values.yaml
    - kind: Secret
      name: forgejo-db-v1-app
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
