image:
  tag: 14.0.2-rootless
  digest: sha256:5552c9e25f353760420b8ac7a7f0f0a788ff571bbfd8e2c1e93503d3e2e1b87a

gitea:
  admin:
    existingSecret: forgejo-admin
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  config:
    repository:
      DEFAULT_REPO_UNITS: "repo.code,repo.releases,repo.pulls,repo.packages,repo.actions"
      DEFAULT_FORK_REPO_UNITS: "repo.code,repo.releases,repo.pulls"
      DEFAULT_MIRROR_REPO_UNITS: "repo.code,repo.releases"
    service:
      DISABLE_REGISTRATION: true
    session:
      PROVIDER: db
    database:
      DB_TYPE: postgres
      HOST: forgejo-db-v1-rw
      NAME: app
      USER: app

persistence:
  enabled: true
  create: false
  claimName: forgejo-data

ingress:
  enabled: true
  className: nginx
  annotations:
    hajimari.io/enable: "true"
  hosts:
    - host: &host code.${cluster_domain}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - *host
