---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tryton-db-v2
  namespace: default
  annotations:
    cnpg.local/backup-revision: "v1"
    cnpg.local/restore-revision: "v1"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4-10
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: tryton
      owner: tryton
      secret:
        name: tryton-db-v2-app
