---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tryton-db-v2-app
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tryton-db-v2-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: apps/tryton/db
        property: username
    - secretKey: password
      remoteRef:
        key: apps/tryton/db
        property: password
    - secretKey: pgpass
      remoteRef:
        key: apps/tryton/db
        property: pgpass
